name: cryptonite-app
services:
  web:
    container_name: cryptonite-web
    build:
      context: ./
      target: final
    develop:
      watch:
        - path: ./server/package.json
          action: rebuild
        - path: ./server/index.js
          target: app/index.js
          action: sync
    ports:
      - '3000:3000'
    environment:
      - CONN_STR=mongodb://admin:admin@mongodb
    depends_on:
      - mongodb
      
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - type: bind
        source: ./data
        target: /data/db